openapi: 3.0.3
info:
  title: youboost Auth Service API
  description: API сервиса аутентификации и авторизации
  version: 0.0.0

paths:
  /auth/register:
    post:
      summary: Регистрация нового пользователя
      tags:
        - Auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - username
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: SecurePassword123!
                username:
                  type: string
                  minLength: 3
                  maxLength: 30
                  pattern: '^[a-zA-Z0-9_]+$'
                  example: john_doe
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  username:
                    type: string
                  verificationRequired:
                    type: boolean
                    description: Требуется ли верификация email
        '400':
          $ref: '../openapi.yaml#/components/responses/BadRequest'
        '409':
          description: Пользователь уже существует
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'

  /auth/login:
    post:
      summary: Вход в систему
      tags:
        - Auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT access token
                  refreshToken:
                    type: string
                    description: Refresh token для обновления access token
                  expiresIn:
                    type: integer
                    description: Время жизни access token в секундах
                    example: 3600
                  tokenType:
                    type: string
                    example: Bearer
        '400':
          $ref: '../openapi.yaml#/components/responses/BadRequest'
        '401':
          description: Неверные учетные данные
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'

  /auth/refresh:
    post:
      summary: Обновление access token
      tags:
        - Auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Token успешно обновлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  expiresIn:
                    type: integer
                    example: 3600
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'

  /auth/logout:
    post:
      summary: Выход из системы
      tags:
        - Auth
      responses:
        '200':
          description: Успешный выход
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'

  /auth/me:
    get:
      summary: Получение информации о текущем пользователе
      tags:
        - Auth
      responses:
        '200':
          description: Информация о пользователе
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  username:
                    type: string
                  roles:
                    type: array
                    items:
                      type: string
                      enum: [user, admin]
                  verified:
                    type: boolean
                  createdAt:
                    type: string
                    format: date-time
        '401':
          $ref: '../openapi.yaml#/components/responses/Unauthorized'

  /auth/verify-email:
    post:
      summary: Верификация email адреса
      tags:
        - Auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: Verification token из email
      responses:
        '200':
          description: Email успешно верифицирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          $ref: '../openapi.yaml#/components/responses/BadRequest'

  /auth/forgot-password:
    post:
      summary: Запрос на восстановление пароля
      tags:
        - Auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Письмо с инструкциями отправлено
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true

  /auth/reset-password:
    post:
      summary: Сброс пароля
      tags:
        - Auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - newPassword
              properties:
                token:
                  type: string
                  description: Reset token из email
                newPassword:
                  type: string
                  format: password
                  minLength: 8
      responses:
        '200':
          description: Пароль успешно изменен
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          $ref: '../openapi.yaml#/components/responses/BadRequest'
